### ISSUE TITLE
Write speed low

### ISSUE THREAD

**Issue by prcode** [davdenic/i5-10600K-ASUS-Z490m-iGpu-opencore-hackintosh#1]
Hey man, first of all thanks for this EFI, I'm using it on my set up (i5-10400 iGPU only) and it works very well.
One thing I noticed that the write speed is a bit slow, using ‎Blackmagic Disk Speed I got ~400mb for writes and ~3000mb for reads (my disk is rated 3000MB/s write speed and 3500MB/s read speed). 

Do you know what the issue could be?

Thanks

**Comment by davdenic** [comment]
> Do you know what the issue could be?

no, my speed is ok, but eventually you can try the NVME fix from dortania guide.
https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html#fixing-nvme
Let me know if you solve.

**Comment by davdenic** [comment]
@prcode 
FYI i've just updated to 0.7.2 replacing VBoxHfs to HfsPlus. 

If you still have the issue please report again
