### ISSUE TITLE
hi  can i use this EFI？

### ISSUE THREAD

**Issue by portau2005** [davdenic/i5-10600K-ASUS-Z490m-iGpu-opencore-hackintosh#2]
i5-10600k--B460M AORUS PRO--GTX 750Ti

**Comment by davdenic** [comment]
it's a different mobo, better if you start fresh with dortania guide and use my EFI just as comparison. 
Your GTX will not work on Catalina as you probably know.

**Comment by portau2005** [comment]
thank you
I know my gtx is up to High Sierra 10.13.6.
I will refer to your EFI and thanks again for getting back to me.



在 2020-10-09 14:48:01，"David Denicolò" <notifications@github.com> 写道：

it's a different mobo, better if you start fresh with dortania guide and use my EFI just as comparison.
Your GTX will not work on Catalina as you probably know.
